version: 2

############################################################################

references:
   build_job_steps: &build_job_steps
      steps:
         - checkout
         - run:
            name: Preparing OS
            command: .circleci/jobs/${CIRCLE_JOB}/prepare-box.sh
         - run:
            name: Creating build
            command: |
               source .circleci/get-env.sh;
               ./build.pl \
                  --build-type="$ZIMBRA_CI_BUILD_TYPE" \
                  --build-hostname="$ZIMBRA_CI_BUILD_HOSTNAME" \
                  --build-release="$ZIMBRA_CI_BUILD_RELEASE" \
                  --build-release-no="$ZIMBRA_CI_BUILD_RELEASE_NO" \
                  --build-release-candidate="$ZIMBRA_CI_BUILD_RELEASE_CANDIDATE" \
                  --build-thirdparty-server="$ZIMBRA_CI_THIRDPARTY_SERVER" \
                  --deploy-url-prefix="https://$ZIMBRA_CI_DEPLOY_HOSTNAME/$ZIMBRA_CI_DEPLOY_PATH" \
                  --git-default-branch="$ZIMBRA_CI_GIT_DEFAULT_BRANCH" \
                  "${ZIMBRA_CI_OVERRIDES[@]}" \
                  --build-os="$ZIMBRA_BUILD_OS" \
                  --build-no="$CIRCLE_BUILD_NUM" \
                  --build-ts="$(date "+%Y%m%d%M%H%S")" \
                  --ant-options="-DskipTests=1" \
                  --no-interactive \
               2>&1 | tee -a build.log;
               mkdir -p ../BUILDS
               mv build.log ../BUILDS/build-${ZIMBRA_OS_TAG}.log
         - store_artifacts:
            path: ../BUILDS
         - persist_to_workspace:
            root: ../BUILDS
            paths: ./*

   stub_build_job_steps: &stub_build_job_steps
      steps:
         - run:
            name: Creating nothing
            command: |
               date
               echo nothing

   deploy_s3_job_steps: &deploy_s3_job_steps
      steps:
         - checkout
         - run:
            name: Preparing OS
            command: .circleci/jobs/${CIRCLE_JOB/@?*/}/prepare-box.sh
         - attach_workspace:
            at: ../BUILDS
         - deploy:
            command: .circleci/jobs/${CIRCLE_JOB/@?*/}/deploy.sh

   deploy_ec2_job_steps: &deploy_ec2_job_steps
      steps:
         - checkout
         - run:
            name: Preparing OS
            command: .circleci/jobs/${CIRCLE_JOB/@?*/}/prepare-box.sh
         - attach_workspace:
            at: ../BUILDS
         - deploy:
            command: .circleci/jobs/${CIRCLE_JOB/@?*/}/deploy.sh install

   deploy_ec2_upgrade_job_steps: &deploy_ec2_upgrade_job_steps
      steps:
         - checkout
         - run:
            name: Preparing OS
            command: .circleci/jobs/${CIRCLE_JOB/@?*/}/prepare-box.sh
         - attach_workspace:
            at: ../BUILDS
         - deploy:
            command: .circleci/jobs/${CIRCLE_JOB/@?*/}/deploy.sh upgrade

############################################################################

jobs:
   build_u16:
      working_directory: ~/zm-build
      shell: /bin/bash -eo pipefail
      environment:
         - ZIMBRA_OS_TAG: u16
         - ZIMBRA_BUILD_OS: UBUNTU16_64
      docker:
         - image: zimbra/zm-base-os:devcore-ubuntu-16.04
      <<: *build_job_steps

   build_u14:
      working_directory: ~/zm-build
      shell: /bin/bash -eo pipefail
      environment:
         - ZIMBRA_OS_TAG: u14
         - ZIMBRA_BUILD_OS: UBUNTU14_64
      docker:
         - image: zimbra/zm-base-os:devcore-ubuntu-14.04
      <<: *build_job_steps

   build_u12:
      working_directory: ~/zm-build
      shell: /bin/bash -eo pipefail
      environment:
         - ZIMBRA_OS_TAG: u12
         - ZIMBRA_BUILD_OS: UBUNTU12_64
      docker:
         - image: zimbra/zm-base-os:devcore-ubuntu-12.04
      <<: *build_job_steps

   build_c7:
      working_directory: ~/zm-build
      shell: /bin/bash -eo pipefail
      environment:
         - ZIMBRA_OS_TAG: c7
         - ZIMBRA_BUILD_OS: RHEL7_64
      docker:
         - image: zimbra/zm-base-os:devcore-centos-7
      <<: *build_job_steps

   build_c6:
      working_directory: ~/zm-build
      shell: /bin/bash -eo pipefail
      environment:
         - ZIMBRA_OS_TAG: c6
         - ZIMBRA_BUILD_OS: RHEL6_64
      docker:
         - image: zimbra/zm-base-os:devcore-centos-6
      <<: *build_job_steps

   deploy_s3:
      working_directory: ~/zm-build
      shell: /bin/bash -eo pipefail
      docker:
         - image: zimbra/zm-base-os:core-ubuntu
      <<: *deploy_s3_job_steps

   deploy_ec2@app1_install:
      working_directory: ~/zm-build
      shell: /bin/bash -eo pipefail
      docker:
         - image: zimbra/zm-base-os:core-ubuntu
      <<: *deploy_ec2_job_steps

   deploy_ec2@app1_upgrade:
      working_directory: ~/zm-build
      shell: /bin/bash -eo pipefail
      docker:
         - image: zimbra/zm-base-os:core-ubuntu
      <<: *deploy_ec2_upgrade_job_steps

############################################################################

workflows:
   version: 2
   build_and_deploy:
      jobs:
         - build_u16
         - build_u14
         - build_u12
#         - build_c7    (core dump issue while running ant)
         - build_c6
         - deploy_s3_hold:
            type: approval
            requires:
               - build_u16
               - build_u14
               - build_u12
#               - build_c7    (core dump issue while running ant)
               - build_c6
         - deploy_s3:
            requires:
               - deploy_s3_hold
         - app1_ec2_install:
            type: approval
            requires:
               - build_u16
         - app1_ec2_upgrade:
            type: approval
            requires:
               - build_u16
         - deploy_ec2@app1_install:
            requires:
               - app1_ec2_install
         - deploy_ec2@app1_upgrade:
            requires:
               - app1_ec2_upgrade
